import { StyleSheet, Text, TextInput, View } from 'react-native';

import { SetForgeColors } from '@/constants/setforge-theme';
import { ActionButton, CoachShell, PageHeading, Panel, StatusBadge, coachStyles } from '@/features/coach/coach-ui';

const blocks = [
  { name: 'Bench Press', sets: [['1','8','70 kg'],['2','8','70 kg'],['3','8','70 kg']] },
  { name: 'Incline Dumbbell Press', sets: [['1','10','24 kg'],['2','10','24 kg'],['3','10','24 kg']] },
  { name: 'Cable Row', sets: [['1','12','55 kg'],['2','12','55 kg'],['3','12','55 kg']] },
];

export default function WorkoutBuilderScreen(){return <CoachShell><View style={coachStyles.page}><PageHeading title="Workout builder" subtitle="Create a structured session with clear progression targets." actions={<><ActionButton label="Save draft" secondary/><ActionButton label="Publish template"/></>}/><View style={styles.columns}><View style={styles.main}><Panel style={styles.form}><Text style={styles.label}>WORKOUT NAME</Text><TextInput defaultValue="Upper Body A" style={styles.input}/><View style={styles.two}><View style={styles.field}><Text style={styles.label}>TRAINING FOCUS</Text><TextInput defaultValue="Strength / hypertrophy" style={styles.input}/></View><View style={styles.field}><Text style={styles.label}>EST. DURATION</Text><TextInput defaultValue="55 minutes" style={styles.input}/></View></View></Panel>{blocks.map((block,index)=><Panel key={block.name} style={styles.exercise}><View style={styles.exerciseHeader}><View><Text style={styles.order}>EXERCISE {index+1}</Text><Text style={styles.exerciseName}>{block.name}</Text></View><Text style={styles.more}>•••</Text></View><View style={styles.setHead}><Text style={styles.setNo}>SET</Text><Text style={styles.setCell}>REPS</Text><Text style={styles.setCell}>LOAD</Text><Text style={styles.setWide}>COACHING NOTE</Text></View>{block.sets.map(set=><View key={set[0]} style={styles.setRow}><Text style={styles.setNo}>{set[0]}</Text><TextInput defaultValue={set[1]} style={[styles.setInput,styles.setCell]}/><TextInput defaultValue={set[2]} style={[styles.setInput,styles.setCell]}/><TextInput placeholder="Optional cue…" placeholderTextColor={SetForgeColors.textDisabled} style={[styles.setInput,styles.setWide]}/></View>)}<Text style={styles.addSet}>+ ADD SET</Text></Panel>)}</View><View style={styles.rail}><Panel style={styles.summary}><Text style={coachStyles.sectionTitle}>Template summary</Text><View style={styles.summaryRow}><Text style={styles.muted}>Exercises</Text><Text style={styles.value}>3</Text></View><View style={styles.summaryRow}><Text style={styles.muted}>Working sets</Text><Text style={styles.value}>9</Text></View><View style={styles.summaryRow}><Text style={styles.muted}>Estimated time</Text><Text style={styles.value}>55m</Text></View><View style={styles.line}/><StatusBadge>Draft</StatusBadge><Text style={styles.copy}>Changes are saved locally while you build this workout.</Text></Panel><Panel style={styles.summary}><Text style={coachStyles.sectionTitle}>Exercise library</Text><TextInput placeholder="Search exercises…" placeholderTextColor={SetForgeColors.textSecondary} style={styles.input}/>{['Overhead Press','Lat Pulldown','Lateral Raise','Triceps Extension'].map(x=><View key={x} style={styles.libraryRow}><Text style={styles.value}>{x}</Text><Text style={styles.add}>+</Text></View>)}</Panel></View></View></View></CoachShell>}
const styles=StyleSheet.create({columns:{flexDirection:'row',gap:24,alignItems:'flex-start'},main:{flex:1,gap:16},rail:{width:320,gap:16},form:{padding:24,gap:10},label:{color:SetForgeColors.textSecondary,fontFamily:'monospace',fontSize:9},input:{height:44,paddingHorizontal:14,color:SetForgeColors.textPrimary,fontSize:13,borderWidth:1,borderColor:SetForgeColors.border,borderRadius:7,backgroundColor:SetForgeColors.canvas,outlineStyle:'none'} as never,two:{flexDirection:'row',gap:16},field:{flex:1,gap:8},exercise:{padding:20},exerciseHeader:{flexDirection:'row',alignItems:'center',justifyContent:'space-between',paddingBottom:16},order:{color:SetForgeColors.accent,fontFamily:'monospace',fontSize:9},exerciseName:{marginTop:4,color:SetForgeColors.textPrimary,fontSize:17,fontWeight:'800'},more:{color:SetForgeColors.textSecondary},setHead:{height:32,flexDirection:'row',alignItems:'center',gap:10,borderTopWidth:1,borderTopColor:SetForgeColors.border},setRow:{height:48,flexDirection:'row',alignItems:'center',gap:10},setNo:{width:40,color:SetForgeColors.textSecondary,fontFamily:'monospace',fontSize:10},setCell:{width:90},setWide:{flex:1},setInput:{height:36,paddingHorizontal:10,color:SetForgeColors.textPrimary,fontSize:12,borderWidth:1,borderColor:SetForgeColors.border,borderRadius:6,backgroundColor:SetForgeColors.canvas,outlineStyle:'none'} as never,addSet:{marginTop:8,color:SetForgeColors.accent,fontSize:11,fontWeight:'800'},summary:{padding:20,gap:16},summaryRow:{flexDirection:'row',justifyContent:'space-between'},muted:{color:SetForgeColors.textSecondary,fontSize:11},value:{color:SetForgeColors.textPrimary,fontSize:12,fontWeight:'700'},line:{height:1,backgroundColor:SetForgeColors.border},copy:{color:SetForgeColors.textSecondary,fontSize:11,lineHeight:17},libraryRow:{height:42,flexDirection:'row',alignItems:'center',justifyContent:'space-between',borderTopWidth:1,borderTopColor:SetForgeColors.border},add:{color:SetForgeColors.accent,fontSize:18}});
