CREATE TABLE IF NOT EXISTS exercises
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name           VARCHAR(100) NOT NULL,
    primary_muscle VARCHAR(50)  NOT NULL,
    equipment      VARCHAR(50)  NOT NULL,
    instructions   TEXT
);

CREATE TABLE IF NOT EXISTS users
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email        VARCHAR(255) NOT NULL UNIQUE,
    display_name VARCHAR(100) NOT NULL,
    account_type VARCHAR(30)  NOT NULL,
    created_at   TIMESTAMPTZ  NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at   TIMESTAMPTZ  NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT ck_users_account_type
        CHECK (account_type IN ('PERSONAL_TRAINER', 'INDIVIDUAL'))
);

CREATE TABLE IF NOT EXISTS coaching_relationships
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    trainer_id BIGINT      NOT NULL,
    client_id  BIGINT      NOT NULL,
    status     VARCHAR(20) NOT NULL DEFAULT 'PENDING',
    started_at TIMESTAMPTZ,
    ended_at   TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_coaching_relationships_trainer
        FOREIGN KEY (trainer_id) REFERENCES users (id) ON DELETE CASCADE,
    CONSTRAINT fk_coaching_relationships_client
        FOREIGN KEY (client_id) REFERENCES users (id) ON DELETE CASCADE,
    CONSTRAINT ck_coaching_relationships_status
        CHECK (status IN ('PENDING', 'ACTIVE', 'ENDED')),
    CONSTRAINT ck_coaching_relationships_distinct_users
        CHECK (trainer_id <> client_id),
    CONSTRAINT ck_coaching_relationships_dates
        CHECK (ended_at IS NULL OR started_at IS NULL OR ended_at >= started_at)
);

CREATE INDEX IF NOT EXISTS ix_coaching_relationships_trainer
    ON coaching_relationships (trainer_id);

CREATE INDEX IF NOT EXISTS ix_coaching_relationships_client
    ON coaching_relationships (client_id);

CREATE UNIQUE INDEX IF NOT EXISTS uq_coaching_relationships_open_pair
    ON coaching_relationships (trainer_id, client_id)
    WHERE status IN ('PENDING', 'ACTIVE');

CREATE TABLE IF NOT EXISTS workout_templates
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    owner_id    BIGINT       NOT NULL,
    name        VARCHAR(100) NOT NULL,
    description TEXT,
    created_at  TIMESTAMPTZ  NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at  TIMESTAMPTZ  NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_workout_templates_owner
        FOREIGN KEY (owner_id) REFERENCES users (id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS ix_workout_templates_owner
    ON workout_templates (owner_id);

CREATE TABLE IF NOT EXISTS workout_template_exercises
(
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    workout_template_id BIGINT  NOT NULL,
    exercise_id         BIGINT  NOT NULL,
    position            INTEGER NOT NULL,
    notes               TEXT,
    CONSTRAINT fk_workout_template_exercises_template
        FOREIGN KEY (workout_template_id) REFERENCES workout_templates (id) ON DELETE CASCADE,
    CONSTRAINT fk_workout_template_exercises_exercise
        FOREIGN KEY (exercise_id) REFERENCES exercises (id),
    CONSTRAINT uq_workout_template_exercises_position
        UNIQUE (workout_template_id, position),
    CONSTRAINT ck_workout_template_exercises_position
        CHECK (position >= 0)
);

CREATE INDEX IF NOT EXISTS ix_workout_template_exercises_exercise
    ON workout_template_exercises (exercise_id);

CREATE TABLE IF NOT EXISTS workout_template_sets
(
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    template_exercise_id    BIGINT         NOT NULL,
    position                INTEGER        NOT NULL,
    set_type                VARCHAR(20)    NOT NULL DEFAULT 'NORMAL',
    target_reps             INTEGER,
    target_weight           NUMERIC(8, 2),
    target_duration_seconds INTEGER,
    CONSTRAINT fk_workout_template_sets_template_exercise
        FOREIGN KEY (template_exercise_id) REFERENCES workout_template_exercises (id)
            ON DELETE CASCADE,
    CONSTRAINT uq_workout_template_sets_position
        UNIQUE (template_exercise_id, position),
    CONSTRAINT ck_workout_template_sets_position
        CHECK (position >= 0),
    CONSTRAINT ck_workout_template_sets_type
        CHECK (set_type IN ('WARM_UP', 'NORMAL', 'DROP_SET', 'FAILURE')),
    CONSTRAINT ck_workout_template_sets_target_reps
        CHECK (target_reps IS NULL OR target_reps >= 0),
    CONSTRAINT ck_workout_template_sets_target_weight
        CHECK (target_weight IS NULL OR target_weight >= 0),
    CONSTRAINT ck_workout_template_sets_target_duration
        CHECK (target_duration_seconds IS NULL OR target_duration_seconds >= 0)
);
