CREATE TABLE IF NOT EXISTS exercises
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name           VARCHAR(100) NOT NULL,
    primary_muscle VARCHAR(50)  NOT NULL,
    equipment      VARCHAR(50)  NOT NULL,
    exercise_type  VARCHAR(30)  NOT NULL DEFAULT 'WEIGHT_AND_REPS',
    instructions   TEXT,
    CONSTRAINT ck_exercises_type
        CHECK (exercise_type IN ('WEIGHT_AND_REPS', 'TIMED'))
);

CREATE TABLE IF NOT EXISTS users
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email        VARCHAR(255) NOT NULL UNIQUE,
    display_name VARCHAR(100) NOT NULL,
    account_type VARCHAR(30)  NOT NULL,
    created_at   TIMESTAMPTZ  NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at   TIMESTAMPTZ  NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT ck_users_account_type
        CHECK (account_type IN ('PERSONAL_TRAINER', 'INDIVIDUAL'))
);

CREATE TABLE IF NOT EXISTS coaching_relationships
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    trainer_id BIGINT      NOT NULL,
    client_id  BIGINT      NOT NULL,
    status     VARCHAR(20) NOT NULL DEFAULT 'PENDING',
    started_at TIMESTAMPTZ,
    ended_at   TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_coaching_relationships_trainer
        FOREIGN KEY (trainer_id) REFERENCES users (id) ON DELETE CASCADE,
    CONSTRAINT fk_coaching_relationships_client
        FOREIGN KEY (client_id) REFERENCES users (id) ON DELETE CASCADE,
    CONSTRAINT ck_coaching_relationships_status
        CHECK (status IN ('PENDING', 'ACTIVE', 'ENDED')),
    CONSTRAINT ck_coaching_relationships_distinct_users
        CHECK (trainer_id <> client_id),
    CONSTRAINT ck_coaching_relationships_dates
        CHECK (ended_at IS NULL OR started_at IS NULL OR ended_at >= started_at)
);

CREATE INDEX IF NOT EXISTS ix_coaching_relationships_trainer
    ON coaching_relationships (trainer_id);

CREATE INDEX IF NOT EXISTS ix_coaching_relationships_client
    ON coaching_relationships (client_id);

CREATE UNIQUE INDEX IF NOT EXISTS uq_coaching_relationships_open_pair
    ON coaching_relationships (trainer_id, client_id)
    WHERE status IN ('PENDING', 'ACTIVE');

CREATE TABLE IF NOT EXISTS workout_templates
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    owner_id    BIGINT       NOT NULL,
    name        VARCHAR(100) NOT NULL,
    description TEXT,
    created_at  TIMESTAMPTZ  NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at  TIMESTAMPTZ  NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_workout_templates_owner
        FOREIGN KEY (owner_id) REFERENCES users (id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS ix_workout_templates_owner
    ON workout_templates (owner_id);

CREATE TABLE IF NOT EXISTS workout_template_exercises
(
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    workout_template_id BIGINT  NOT NULL,
    exercise_id         BIGINT  NOT NULL,
    position            INTEGER NOT NULL,
    notes               TEXT,
    CONSTRAINT fk_workout_template_exercises_template
        FOREIGN KEY (workout_template_id) REFERENCES workout_templates (id) ON DELETE CASCADE,
    CONSTRAINT fk_workout_template_exercises_exercise
        FOREIGN KEY (exercise_id) REFERENCES exercises (id),
    CONSTRAINT uq_workout_template_exercises_position
        UNIQUE (workout_template_id, position),
    CONSTRAINT ck_workout_template_exercises_position
        CHECK (position >= 0)
);

CREATE INDEX IF NOT EXISTS ix_workout_template_exercises_exercise
    ON workout_template_exercises (exercise_id);

CREATE TABLE IF NOT EXISTS workout_template_sets
(
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    template_exercise_id    BIGINT         NOT NULL,
    position                INTEGER        NOT NULL,
    set_type                VARCHAR(20)    NOT NULL DEFAULT 'NORMAL',
    target_reps             INTEGER,
    target_weight           NUMERIC(8, 2),
    target_time_seconds     INTEGER,
    rest_seconds            INTEGER,
    CONSTRAINT fk_workout_template_sets_template_exercise
        FOREIGN KEY (template_exercise_id) REFERENCES workout_template_exercises (id)
            ON DELETE CASCADE,
    CONSTRAINT uq_workout_template_sets_position
        UNIQUE (template_exercise_id, position),
    CONSTRAINT ck_workout_template_sets_position
        CHECK (position >= 0),
    CONSTRAINT ck_workout_template_sets_type
        CHECK (set_type IN ('WARM_UP', 'NORMAL', 'DROP_SET', 'FAILURE')),
    CONSTRAINT ck_workout_template_sets_target_reps
        CHECK (target_reps IS NULL OR target_reps >= 0),
    CONSTRAINT ck_workout_template_sets_target_weight
        CHECK (target_weight IS NULL OR target_weight >= 0),
    CONSTRAINT ck_workout_template_sets_target_time
        CHECK (target_time_seconds IS NULL OR target_time_seconds > 0),
    CONSTRAINT ck_workout_template_sets_rest
        CHECK (rest_seconds IS NULL OR rest_seconds >= 0)
);

CREATE TABLE IF NOT EXISTS workout_sessions
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id            BIGINT       NOT NULL,
    source_template_id BIGINT,
    name               VARCHAR(100) NOT NULL,
    notes              TEXT,
    status             VARCHAR(20)  NOT NULL DEFAULT 'IN_PROGRESS',
    started_at         TIMESTAMPTZ  NOT NULL DEFAULT CURRENT_TIMESTAMP,
    completed_at       TIMESTAMPTZ,
    created_at         TIMESTAMPTZ  NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at         TIMESTAMPTZ  NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_workout_sessions_user
        FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE,
    CONSTRAINT fk_workout_sessions_source_template
        FOREIGN KEY (source_template_id) REFERENCES workout_templates (id) ON DELETE SET NULL,
    CONSTRAINT ck_workout_sessions_status
        CHECK (status IN ('IN_PROGRESS', 'COMPLETED', 'CANCELLED')),
    CONSTRAINT ck_workout_sessions_completion
        CHECK (
            (status = 'IN_PROGRESS' AND completed_at IS NULL)
            OR (status IN ('COMPLETED', 'CANCELLED') AND completed_at IS NOT NULL)
        ),
    CONSTRAINT ck_workout_sessions_dates
        CHECK (completed_at IS NULL OR completed_at >= started_at)
);

CREATE INDEX IF NOT EXISTS ix_workout_sessions_user_started
    ON workout_sessions (user_id, started_at DESC);

CREATE INDEX IF NOT EXISTS ix_workout_sessions_source_template
    ON workout_sessions (source_template_id);

CREATE TABLE IF NOT EXISTS workout_session_exercises
(
    id                          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    workout_session_id          BIGINT  NOT NULL,
    exercise_id                 BIGINT  NOT NULL,
    source_template_exercise_id BIGINT,
    position                    INTEGER NOT NULL,
    notes                       TEXT,
    CONSTRAINT fk_workout_session_exercises_session
        FOREIGN KEY (workout_session_id) REFERENCES workout_sessions (id) ON DELETE CASCADE,
    CONSTRAINT fk_workout_session_exercises_exercise
        FOREIGN KEY (exercise_id) REFERENCES exercises (id),
    CONSTRAINT fk_workout_session_exercises_source_template_exercise
        FOREIGN KEY (source_template_exercise_id) REFERENCES workout_template_exercises (id)
            ON DELETE SET NULL,
    CONSTRAINT uq_workout_session_exercises_position
        UNIQUE (workout_session_id, position),
    CONSTRAINT ck_workout_session_exercises_position
        CHECK (position >= 0)
);

CREATE INDEX IF NOT EXISTS ix_workout_session_exercises_exercise
    ON workout_session_exercises (exercise_id);

CREATE INDEX IF NOT EXISTS ix_workout_session_exercises_source_template
    ON workout_session_exercises (source_template_exercise_id);

CREATE TABLE IF NOT EXISTS workout_sets
(
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_exercise_id     BIGINT      NOT NULL,
    source_template_set_id  BIGINT,
    position                INTEGER     NOT NULL,
    set_type                VARCHAR(20) NOT NULL DEFAULT 'NORMAL',
    target_reps             INTEGER,
    target_weight           NUMERIC(8, 2),
    target_time_seconds     INTEGER,
    rest_seconds            INTEGER,
    reps                    INTEGER,
    weight                  NUMERIC(8, 2),
    time_seconds            INTEGER,
    distance_meters         NUMERIC(10, 2),
    completed               BOOLEAN     NOT NULL DEFAULT FALSE,
    completed_at            TIMESTAMPTZ,
    CONSTRAINT fk_workout_sets_session_exercise
        FOREIGN KEY (session_exercise_id) REFERENCES workout_session_exercises (id)
            ON DELETE CASCADE,
    CONSTRAINT fk_workout_sets_source_template_set
        FOREIGN KEY (source_template_set_id) REFERENCES workout_template_sets (id)
            ON DELETE SET NULL,
    CONSTRAINT uq_workout_sets_position
        UNIQUE (session_exercise_id, position),
    CONSTRAINT ck_workout_sets_position
        CHECK (position >= 0),
    CONSTRAINT ck_workout_sets_type
        CHECK (set_type IN ('WARM_UP', 'NORMAL', 'DROP_SET', 'FAILURE')),
    CONSTRAINT ck_workout_sets_target_reps
        CHECK (target_reps IS NULL OR target_reps >= 0),
    CONSTRAINT ck_workout_sets_target_weight
        CHECK (target_weight IS NULL OR target_weight >= 0),
    CONSTRAINT ck_workout_sets_target_time
        CHECK (target_time_seconds IS NULL OR target_time_seconds > 0),
    CONSTRAINT ck_workout_sets_rest
        CHECK (rest_seconds IS NULL OR rest_seconds >= 0),
    CONSTRAINT ck_workout_sets_reps
        CHECK (reps IS NULL OR reps >= 0),
    CONSTRAINT ck_workout_sets_weight
        CHECK (weight IS NULL OR weight >= 0),
    CONSTRAINT ck_workout_sets_time
        CHECK (time_seconds IS NULL OR time_seconds >= 0),
    CONSTRAINT ck_workout_sets_distance
        CHECK (distance_meters IS NULL OR distance_meters >= 0),
    CONSTRAINT ck_workout_sets_completion
        CHECK (
            (completed = FALSE AND completed_at IS NULL)
            OR (completed = TRUE AND completed_at IS NOT NULL)
        )
);

-- Upgrade an existing development database. These statements are safe to rerun.
ALTER TABLE exercises
    ADD COLUMN IF NOT EXISTS exercise_type VARCHAR(30) NOT NULL DEFAULT 'WEIGHT_AND_REPS';

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint WHERE conname = 'ck_exercises_type'
    ) THEN
        ALTER TABLE exercises ADD CONSTRAINT ck_exercises_type
            CHECK (exercise_type IN ('WEIGHT_AND_REPS', 'TIMED'));
    END IF;
END
$$;

DO $$
BEGIN
    IF EXISTS (
        SELECT 1 FROM information_schema.columns
        WHERE table_schema = 'public'
          AND table_name = 'workout_template_sets'
          AND column_name = 'target_duration_seconds'
    ) AND NOT EXISTS (
        SELECT 1 FROM information_schema.columns
        WHERE table_schema = 'public'
          AND table_name = 'workout_template_sets'
          AND column_name = 'target_time_seconds'
    ) THEN
        ALTER TABLE workout_template_sets
            RENAME COLUMN target_duration_seconds TO target_time_seconds;
    END IF;
END
$$;

ALTER TABLE workout_template_sets
    DROP COLUMN IF EXISTS target_duration_seconds;
ALTER TABLE workout_template_sets
    ADD COLUMN IF NOT EXISTS rest_seconds INTEGER;
ALTER TABLE workout_template_sets
    DROP CONSTRAINT IF EXISTS ck_workout_template_sets_target_duration;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint
        WHERE conname = 'ck_workout_template_sets_target_time'
    ) THEN
        ALTER TABLE workout_template_sets ADD CONSTRAINT ck_workout_template_sets_target_time
            CHECK (target_time_seconds IS NULL OR target_time_seconds > 0);
    END IF;
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint
        WHERE conname = 'ck_workout_template_sets_rest'
    ) THEN
        ALTER TABLE workout_template_sets ADD CONSTRAINT ck_workout_template_sets_rest
            CHECK (rest_seconds IS NULL OR rest_seconds >= 0);
    END IF;
END
$$;

DO $$
BEGIN
    IF EXISTS (
        SELECT 1 FROM information_schema.columns
        WHERE table_schema = 'public'
          AND table_name = 'workout_sets'
          AND column_name = 'target_duration_seconds'
    ) AND NOT EXISTS (
        SELECT 1 FROM information_schema.columns
        WHERE table_schema = 'public'
          AND table_name = 'workout_sets'
          AND column_name = 'target_time_seconds'
    ) THEN
        ALTER TABLE workout_sets
            RENAME COLUMN target_duration_seconds TO target_time_seconds;
    END IF;
    IF EXISTS (
        SELECT 1 FROM information_schema.columns
        WHERE table_schema = 'public'
          AND table_name = 'workout_sets'
          AND column_name = 'duration_seconds'
    ) AND NOT EXISTS (
        SELECT 1 FROM information_schema.columns
        WHERE table_schema = 'public'
          AND table_name = 'workout_sets'
          AND column_name = 'time_seconds'
    ) THEN
        ALTER TABLE workout_sets
            RENAME COLUMN duration_seconds TO time_seconds;
    END IF;
END
$$;

ALTER TABLE workout_sets
    DROP COLUMN IF EXISTS target_duration_seconds;
ALTER TABLE workout_sets
    DROP COLUMN IF EXISTS duration_seconds;
ALTER TABLE workout_sets
    ADD COLUMN IF NOT EXISTS rest_seconds INTEGER;
ALTER TABLE workout_sets
    DROP CONSTRAINT IF EXISTS ck_workout_sets_target_duration;
ALTER TABLE workout_sets
    DROP CONSTRAINT IF EXISTS ck_workout_sets_duration;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint WHERE conname = 'ck_workout_sets_target_time'
    ) THEN
        ALTER TABLE workout_sets ADD CONSTRAINT ck_workout_sets_target_time
            CHECK (target_time_seconds IS NULL OR target_time_seconds > 0);
    END IF;
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint WHERE conname = 'ck_workout_sets_rest'
    ) THEN
        ALTER TABLE workout_sets ADD CONSTRAINT ck_workout_sets_rest
            CHECK (rest_seconds IS NULL OR rest_seconds >= 0);
    END IF;
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint WHERE conname = 'ck_workout_sets_time'
    ) THEN
        ALTER TABLE workout_sets ADD CONSTRAINT ck_workout_sets_time
            CHECK (time_seconds IS NULL OR time_seconds >= 0);
    END IF;
END
$$;

-- The application connects as setforge_app, while structural SQL is run as postgres.
GRANT USAGE ON SCHEMA public TO setforge_app;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO setforge_app;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO setforge_app;

-- Keep the same application privileges for tables and identity sequences created later by postgres.
ALTER DEFAULT PRIVILEGES IN SCHEMA public
    GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO setforge_app;
ALTER DEFAULT PRIVILEGES IN SCHEMA public
    GRANT USAGE, SELECT ON SEQUENCES TO setforge_app;
