CREATE TABLE exercises
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name           VARCHAR(100) NOT NULL,
    primary_muscle VARCHAR(50)  NOT NULL,
    equipment      VARCHAR(50)  NOT NULL,
    instructions   TEXT
);